image: python:3.10

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Сборка проекта..."
    - echo "Все работает!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

run_tests:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Запуск автотестов..."
    - pytest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
